# render.yaml
services:
  - type: web
    name: choco-backend-api # Assurez-vous que c'est le même nom que votre service Render
    env: node
    # Nouvelle commande de build pour décompresser Chromium manuellement
    buildCommand: 'npm install && node -e "require(\'@sparticuz/chromium\').executablePath.then(p => console.log(\'Chromium path:\', p))"'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Assurez-vous que cette variable est synchronisée depuis votre environnement Render
      - key: PORT
        value: 3001
